Traceback (most recent call last):
  File "c:\users\asus\.conda\envs\unearthed-challenge-name\lib\site-packages\unearthed\cli\commands\submit.py", line 46, in submit
    submission = Submission.fromApi(challenge.challengeId)
  File "c:\users\asus\.conda\envs\unearthed-challenge-name\lib\site-packages\unearthed\core\models\submission.py", line 64, in fromApi
    response.raise_for_status()
  File "c:\users\asus\.conda\envs\unearthed-challenge-name\lib\site-packages\requests\models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error:  for url: https://crowdml.unearthed.solutions/challenges/ddaa176b-d2a6-4766-a790-a7f0c15272ea/submission
